name: CI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim   # job runs inside Python 3.9

    services:
      postgres:
        image: postgres:alpine          # lightweight Postgres image
        ports:
          - 5432:5432                  # expose default Postgres port
        env:
          POSTGRES_PASSWORD: pgs3cr3t  # password used in local Makefile
          POSTGRES_DB: testdb          # database name for tests
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
